CREATE TABLE IF NOT EXISTS COURSES(ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL,
    LENGTH INT NOT NULL,
    URL VARCHAR NOT NULL,
    NOTES VARCHAR);

CREATE TABLE IF NOT EXISTS AUTHORS(ID IDENTITY PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    HANDLE VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS CALIFICACION(ID IDENTITY PRIMARY KEY NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    COURSE_ID VARCHAR NOT NULL,
    NOTA INTEGER NOT NULL);